version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: jokes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jokes-network

  jokes-api:
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/jokes_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - jokes-network

volumes:
  postgres_data:

networks:
  jokes-network:
    driver: bridge